"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1&n7@(eq(f7j#4i5)ooud6jn+%8!f+@bo_y!rv^=ihv-ij&%&('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# alowed_host = config('ALLOWED_HOSTS')
# ALLOWED_HOSTS = alowed_host.split(',')
ALLOWED_HOSTS = ["*"]
CORS_ORIGIN_ALLOW_ALL = True
# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'app.apps.ProfileAppConfig',
    "corsheaders",
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.IsAuthenticated'
    ],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'rest_framework_simplejwt.authentication.JWTAuthentication',
    # ],
    # 'DEFAULT_PAGINATION_CLASS': 'app.http.paginations.StandardPagination',
    # 'PAGE_SIZE': 20
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.http.middlewares.authen_user_middleware.AuthenUserMiddleware'
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('MYSQL_DATABASE_DB'),
        'USER': config('MYSQL_DATABASE_USER'),
        'PASSWORD': config('MYSQL_DATABASE_PASSWORD'),
        'HOST': config('MYSQL_DATABASE_HOST'),
        'PORT': config('MYSQL_DATABASE_PORT'),     
        # "POOL_OPTIONS": {
        #     'POOL_SIZE': 200,
        #     'MAX_OVERFLOW': 50,
        #     'RECYCLE': 10*60
        # }   
        # "CONN_MAX_AGE": 300,
        # "CONN_HEALTH_CHECKS": True
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APP_ENV = config('APP_ENV', 'production')

if(APP_ENV == 'local'):
    PROFILE_SERVICE = "http://myptpdx-api-stag.fpt.net/mypt-profile-api"
    PROXIES = { 
                "http"  : "http://proxy.hcm.fpt.vn:80", 
                "https" : "http://proxy.hcm.fpt.vn:80", 
            }
elif(APP_ENV == 'staging'):
    PROFILE_SERVICE = "http://mypt-profile-api-staging/mypt-profile-api"
    PROXIES = { 
                "http"  : "http://proxy.hcm.fpt.vn:80", 
                "https" : "http://proxy.hcm.fpt.vn:80", 
            }
elif(APP_ENV == 'production'):
    PROFILE_SERVICE = "http://mypt-profile-api/mypt-profile-api"
    PROXIES = { 
                "http"  : "http://proxy.hcm.fpt.vn:80", 
                "https" : "http://proxy.hcm.fpt.vn:80", 
            }


REDIS_HOST_CENTRALIZED = config("CENTRALIZED_SESSION_REDIS_HOST")
REDIS_PORT_CENTRALIZED = int(config("CENTRALIZED_SESSION_REDIS_PORT"))
REDIS_PASSWORD_CENTRALIZED = config("CENTRALIZED_SESSION_REDIS_PASSWORD")
REDIS_DATABASE_CENTRALIZED = int(config("CENTRALIZED_SESSION_REDIS_DATABASE"))

SERVICE_REDIS_HOST = config("SERVICE_REDIS_HOST")
SERVICE_REDIS_PORT = int(config("SERVICE_REDIS_PORT"))
SERVICE_REDIS_PASSWORD = config("CENTRALIZED_SESSION_REDIS_PASSWORD")

NOTIFICATION_REDIS_DATABASE = int(config("NOTIFICATION_REDIS_DATABASE"))


APP_ENVIRONMENT = config('APP_ENV')
ENV_APP = config('APP_ENV')

TIME_ZONE = 'Asia/Saigon'

USE_I18N = True

USE_TZ = False

import os
DJANGO_ALLOW_ASYNC_UNSAFE = True
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

